src/Entity/Property.php
<?php

namespace App\Entity;

use App\Entity\Option;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertyRepository;
use Cocur\Slugify\Slugify;            
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert; // pour gerer les valisations sur form
//  @UniqueEntity("title") pour qu le titr soit unique

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{

    const HEAT = [
        0 =>'Electrique',
        1 =>'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */ 
    private $id;

    /**
 * @ORM\Column(type="string", length=255, nullable=true)  // Ajoutez nullable=true
 */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *  mimeTypes="image/png"
     * )
     * @vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;




    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */      
    private $address;
    // @Assert\Regex("/^[0-9]{5}$/") format prenant les chifr de 0 à 9 pour 5 caratèr
    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

   

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title); 
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    // pour afficher le prix de facon espacée
    public function getFormattedPrice() : string
    {
        return number_format($this->price,0,'',' ');
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }


    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }


    /**
     * @return null|string
     */
    public function getFileName(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Property
     */
    public function setFileName(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
       if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTimeImmutable('now');
      }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

   

    
    }

templates/pages/home.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}EasyImmo - Votre agence immobilière{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">
        <link rel="stylesheet" href="{{ asset('build/app.css') }}">
        {% block stylesheets %}{% endblock %}
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="{{ path('home') }}">
                <img src="{{ asset('images/Logo_EasyImmo.png') }}" alt="EasyImmo Logo" style="height: 60px;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link{% if current_menu is defined and current_menu == 'properties' %} active{% endif %}" href="{{ path('property.index') }}">Acheter</a>
                    </li>
                </ul>
                
                {% if app.user %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{ path('logout') }}" class="nav-link">Se déconnecter</a>              
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{ path('login') }}" class="nav-link">Connexion</a>              
                        </li>
                    </ul>
                {% endif %}
            </div>
        </nav>

        {% block body %}
            <div class="jumbotron jumbotron-fluid bg-primary text-white text-center py-5">
                <div class="container">
                    <h1 class="display-4 mb-4">EasyImmo</h1>
                    <p class="lead">
                        Votre partenaire immobilier de confiance depuis plusieurs années.<br>
                        Spécialistes de l'achat, vente et location dans tout le Cameroun.
                    </p>
                    <hr class="my-4 bg-light">
                    <div class="row mt-5">
                        <div class="col-md-4">
                            <i class="fas fa-home fa-3x mb-3"></i>
                            <h3>Expertise Locale</h3>
                            <p>Notre équipe connaît parfaitement le marché immobilier local</p>
                        </div>
                        <div class="col-md-4">
                            <i class="fas fa-euro-sign fa-3x mb-3"></i>
                            <h3>Meilleurs Prix</h3>
                            <p>Nous négocions pour vous les conditions les plus avantageuses</p>
                        </div>
                        <div class="col-md-4">
                            <i class="fas fa-lock fa-3x mb-3"></i>
                            <h3>Sécurité</h3>
                            <p>Transactions 100% sécurisées avec accompagnement juridique</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container py-5">
                <h2 class="text-center mb-5">Nos dernières offres</h2>
                <div class="row">
                    {% for property in properties %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100 shadow-sm">
                            {% if property.filename %}
                                <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" 
                                     class="card-img-top" 
                                     alt="{{ property.title }}"
                                     style="height: 200px; object-fit: cover;">
                            {% else %}
                                <img src="{{ '/images/properties/placeholder.jpg' | imagine_filter('thumb') }}" 
                                     class="card-img-top" 
                                     alt="Image par défaut"
                                     style="height: 200px; object-fit: cover;">
                            {% endif %}
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">
                                    <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}" class="text-dark">
                                        {{ property.title }}
                                    </a>
                                </h5>
                                <p class="card-text text-muted">
                                    <i class="fas fa-map-marker-alt"></i> {{ property.city }} ({{ property.postalCode }})
                                </p>
                                <div class="text-primary mt-auto" style="font-weight: bold; font-size: 1.5rem;">
                                    {{ property.formattedPrice }} €
                                </div>
                                <div class="mt-2">
                                    <span class="badge bg-secondary">
                                        <i class="fas fa-bed"></i> {{ property.bedrooms }} chambres
                                    </span>
                                    <span class="badge bg-secondary ms-2">
                                        <i class="fas fa-ruler-combined"></i> {{ property.surface }} m²
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                
                <div class="text-center mt-4">
                    <a href="{{ path('property.index') }}" class="btn btn-primary btn-lg">
                        Voir toutes nos propriétés <i class="fas fa-arrow-right ms-2"></i>
                    </a>
                </div>
            </div>
        {% endblock %}
        
        <footer class="bg-dark text-white py-4 mt-5">
            <div class="container text-center">
                <p>&copy; {{ 'now'|date('Y') }} EasyImmo - Tous droits réservés</p>
                <p>
                    <a href="#" class="text-white">Mentions légales</a> | 
                    <a href="#" class="text-white">Contact</a> | 
                    <a href="#" class="text-white">CGU</a>
                </p>
            </div>
        </footer>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="{{ asset('build/app.js') }}"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>