src/Entity/Property.php
<?php

namespace App\Entity;

use App\Entity\Option;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertyRepository;
use Cocur\Slugify\Slugify;            
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert; // pour gerer les valisations sur form
//  @UniqueEntity("title") pour qu le titr soit unique

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{

    const HEAT = [
        0 =>'Electrique',
        1 =>'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */ 
    private $id;

    /**
 * @ORM\Column(type="string", length=255, nullable=true)  // Ajoutez nullable=true
 */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *  mimeTypes="image/png"
     * )
     * @vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @Assert\Length(min=5, max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;




    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */      
    private $address;
    // @Assert\Regex("/^[0-9]{5}$/") format prenant les chifr de 0 à 9 pour 5 caratèr
    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

   

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title); 
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    // pour afficher le prix de facon espacée
    public function getFormattedPrice() : string
    {
        return number_format($this->price,0,'',' ');
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }


    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }


    /**
     * @return null|string
     */
    public function getFileName(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Property
     */
    public function setFileName(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
       if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTimeImmutable('now');
      }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

   

    
    }

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
//use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
//use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices() 
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required'=>false,
                'choice_label' => 'name',
                'multiple' =>true
            ])
            ->add('imageFile', FileType::class, [
                'required' =>false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
            
        ; // ->add('city',null, ['label' =>'Ville']) ca va remplacer city par vill sur le formulair
    }      //'choices' => Property::HEAT remplacé par la method crée getchoice car HEAT renvoi 0 ou 1 au niveau de la selection

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]); 
        }// 'translation_domain' => 'forms' ajoutée pour la traduction des labels
            // ensuite on part dans translation creer le ficher quon a appelé forms.fr.yaml 
            // ensuite dans config/packages/translation.yaml on change local "en" en "fr"

    public function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }


        }

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Form\ContactType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use Symfony\Component\Form\Form;
//use Symfony\Component\Form\FormTypeInterface;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;



class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository; 
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;

    }

    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        

                                                                      /*pour recuperer ds bd mthod1 $repository = $this->getDoctrine()->getRepository(Property::class);
                                                                                //dump($repository);                                                   dump($repository);  

                                                                    $repository = $this->repository->findAllVisible();         
                                                                    $property[0]->setSold(true);
                                                                    $this->em->flush();*/

          // pour faire la recherch il faut créer une entité non reliée à la bd sans passser par l'invite de command qui va gerer la recher
          //créer un formulair sur invit de command php bin/console make: form on lui donne un nom apres on l'indiq \App\Entity\PropertySearch
          //gerer le traitement ds le controller                                                          

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1), /*page number*/
            10  /*limit per page*/  
    );  //$properties = $this->repository->findAllVisible();  remplacé pour la pagination en faisant linjection dans index() un ficher knp_paginator.yml a été crée ds ce sens dans config/pakage  où on a inséré tout un bloq d'instruction                                                     
        return $this->render('property/index.html.twig', [
         'current_menu' => 'properties',
         'properties'   => $properties,
        'form' => $form->createView()]);           //return new Response('les biens');  //, ['current_menu' => 'properties'] ajouté pour faire activer le bouton acheter aptres clic. le nom du controleur current_menu peut etr remplacé par nimporte quoi .la suite se fait sur le bouton achter dans base.html.twig
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     *@param Property @property
     *@return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response 
    {
        // la classe contactnotification a été crée pour effectuer le contact 
        if ($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm( ContactType::class, $contact);
        $form->handleRequest($request);// auu niveau du form gere la requte
        if ($form->isSubmitted() && $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success','votre email a été bien envoyé');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        /*public function show($slug, $id): Response
        $property= $this->repository->find($id); remplacé par linjection on obtient aussi le mem resutat
        et pas besoin de recuperer l'id car il le fera grace à la route où l'id est deja defini. l'injection en question c'est public function show(Property $property) : response
        la re
        */
        return $this->render('property/show.html.twig',[
            'property'       => $property,
            'current_menu'   => 'properties',
            'form'           => $form->createView()]);
    }
}
/*$property = new Property();
        $property->setTitle('Mon premier bien') 
                 ->setPrice(200000)
                 ->setRooms(4)
                 ->setBedrooms(4)
                 ->setDescription('une petite description')   
                 ->setSurface(60)
                 ->setFloor(4)
                 ->setHeat(1)  
                 ->setCity('Monpellier')
                 ->setAddress('15 Boulevard Gambetta')
                 ->setPostalCode('34000')
                 ->setEfface('moto');  
            $em = $this->getDoctrine()->getManager();
            $em->persist($property);
            $em->flush();*/

templates/property/_property.html.twig
<div class="card mb-4">
{% if property.filename %}
    <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height:auto;">
    <!-- "images/properties/{{ property.filename}}" remplacé par vich_uploader qui fait la meme chose-->
    {% else %}
    <img src="{{ asset('/images/properties/cat2.PNG'  | imagine_filter('thumb') )}}" alt="card-img-top" style="width: 100%; height:auto;">

{% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id})}}">
            {{ property.title}}
            </a>
        </h5>
        <p class="card-text">{{ property.surface}}m² - {{ property.city }} ({{ property.postalcode}}) </p>
        <div class="text-primary" style="font-size:2rem; font-weight: bold;">
            {{ property.formattedPrice }} Francs CFA
        </div>
    </div>
</div>   

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{%block title 'Tous nos biens'%}
{% block body %}
    <div class="jumbotron">
        <div class="container">
        {{ form_start(form) }}
        <div class="form-row align-items-end">
            <div class="col">
                {{ form_row(form.minSurface) }}
            </div>
            <div class="col">
                {{ form_row(form.maxPrice) }}
            </div>

            <div class="col">
                {{ form_row(form.options) }}
            </div>

            <div class="col">
                <div class="form-group"><button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
        </div>
        {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1> voir tous nos biens</h1>
         <div class="row">
             {% for property in properties %}
        <div class="col-md-4">
            {% include('property/_property.html.twig') %}
        </div>    
            {% endfor %}
        </div>
            <div class="pagination">
                {{ knp_pagination_render(properties) }}
            </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ property.title }}{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>   
            {% endfor %}

            {% if not form.vars.valid %}
                <div class="alert alert-danger">
                    Erreur de soumission veuillez vérifier les informations
                </div>
            {% endif %}

            <div class="row">
                <div class="col-md-8">
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height:auto;">
                    {% else %}
                        <img src="{{ '/images/properties/cat2.PNG' | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height:auto;">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice }} F</div>
                    <button class="btn btn-primary" id="contactButton"{% if form.vars.submitted %} style="display: none;"{% endif %}>
                        Contacter l'Agence
                    </button>
                    <div id="contactForm" class="mt-4"{% if not form.vars.submitted %} style="display:none;"{% endif %}>
                        {{ form_start(form) }}
                            <div class="row">
                                <div class="col">{{ form_row(form.firstname) }}</div>
                                <div class="col">{{ form_row(form.lastname) }}</div>
                            </div>
                            <div class="row">
                                <div class="col">{{ form_row(form.phone) }}</div>
                                <div class="col">{{ form_row(form.email) }}</div>
                            </div>
                            {{ form_rest(form) }}
                            <div class="form-group">
                                <button class="btn btn-primary">Envoyer</button>
                            </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambre</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const contactButton = document.getElementById('contactButton');
            const contactForm = document.getElementById('contactForm');
            
            if (contactButton && contactForm) {
                contactButton.addEventListener('click', function(e) {
                    e.preventDefault();
                    contactButton.style.display = 'none';
                    contactForm.style.display = 'block';
                });
            }
        });
    </script>
{% endblock %}